/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_PANPROTO_C__
#define __RUST_PANPROTO_C__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {
    /** <No documentation available> */
    uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_uint8_t;

/** \brief
 *  Free a byte buffer returned by panproto-c.
 *
 *  The host must call this on every `repr_c::Vec<u8>` it receives, or
 *  memory leaks. Calling twice on the same buffer is undefined
 *  behavior; do not double-free. The Haskell binding's
 *  `pp_buf_free_at` glue zeroes the storage in place so a stale
 *  `Vec_uint8_t` record cannot be passed back; non-Haskell callers
 *  should follow the same discipline.
 *
 *  The drop is wrapped in [`std::panic::catch_unwind`] so that a stray
 *  panic in the deallocator (or in a `Vec` whose contents the host
 *  corrupted) cannot unwind across the FFI boundary, which is
 *  undefined behavior. A caught panic is silently suppressed; the
 *  host has no return channel here. This is the same panic-safety
 *  posture as every other entry point in this module.
 */
void
pp_buf_free (
    Vec_uint8_t buf);

/** \brief
 *  Free a handle, marking its slab slot reusable.
 *
 *  Double-free is safe: a freed slot stays freed.
 */
int32_t
pp_handle_free (
    uint32_t handle);

/** \brief
 *  Initialize the panproto-c runtime.
 *
 *  Installs a process-global Rust panic hook that suppresses the
 *  default stderr output. Panics are still observable: every entry
 *  point in this module catches them via [`crate::panic::guard`] and
 *  stashes the message in the thread-local last-error slot, which
 *  the host retrieves via [`pp_last_error_take`]. Without this hook
 *  the default Rust handler would print every caught panic to
 *  stderr before `guard` could report it, which is noisy and
 *  surprising for hosts that already report errors through the
 *  status-code channel.
 *
 *  Idempotent: calling more than once just re-installs the same
 *  hook. Always returns [`PpStatus::Ok`]. The slab and last-error
 *  slots are thread-local `RefCell`s that initialize lazily, so they
 *  do not need explicit setup.
 */
int32_t
pp_init (void);

/** \brief
 *  Take the last error envelope as a CBOR byte vector.
 *
 *  On `PpStatus::Ok`, `out` is populated with the freshly allocated
 *  bytes; the host must release them via [`pp_buf_free`]. If no error
 *  is pending, `out` receives an empty buffer and the status is
 *  [`PpStatus::Ok`].
 */
int32_t
pp_last_error_take (
    Vec_uint8_t * out);

/** \brief
 *  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_ref_uint8 {
    /** \brief
     *  Pointer to the first element (if any).
     */
    uint8_t const * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_ref_uint8_t;

/** \brief
 *  Ingest a CBOR-encoded [`Protocol`] specification and register it
 *  in the slab.
 *
 *  On success, `out_handle` is set to a fresh handle and [`PpStatus::Ok`]
 *  is returned. On CBOR decode failure, [`PpStatus::Serialization`] is
 *  returned and `out_handle` is left untouched.
 */
int32_t
pp_protocol_define (
    slice_ref_uint8_t spec,
    uint32_t * out_handle);

/** \brief
 *  Serialize the protocol referenced by `proto` to CBOR.
 *
 *  On success, `out` is populated with freshly allocated CBOR bytes;
 *  the host must release them via `pp_buf_free`. Common failure modes
 *  are [`PpStatus::InvalidHandle`] and (once additional resource
 *  variants exist) [`PpStatus::TypeMismatch`].
 */
int32_t
pp_protocol_serialize (
    uint32_t proto,
    Vec_uint8_t * out);

/** \brief
 *  Deserialize a CBOR-encoded `Schema` into the slab.
 *
 *  On success, `out_handle` is set to a fresh handle and
 *  [`PpStatus::Ok`] is returned. On CBOR decode failure,
 *  [`PpStatus::Serialization`] is returned and `out_handle` is left
 *  untouched.
 */
int32_t
pp_schema_from_cbor (
    slice_ref_uint8_t spec,
    uint32_t * out_handle);

/** \brief
 *  Serialize the schema referenced by `schema_handle` to CBOR.
 *
 *  On success, `out` is populated with freshly allocated CBOR bytes;
 *  the host must release them via `pp_buf_free`. Common failure modes
 *  are [`PpStatus::InvalidHandle`] and [`PpStatus::TypeMismatch`]
 *  (when `schema_handle` does not point at a `Schema` resource).
 */
int32_t
pp_schema_to_cbor (
    uint32_t schema_handle,
    Vec_uint8_t * out);

/** \brief
 *  Validate the schema referenced by `schema_handle` against the
 *  protocol referenced by `proto_handle`.
 *
 *  `out_messages` is populated with a CBOR-encoded `Vec<String>` of
 *  human-readable validation messages. An empty list means the schema
 *  is valid against the protocol. The status is always [`PpStatus::Ok`]
 *  on a successful validation pass (regardless of whether the schema
 *  passed validation); validation failures appear in the message list.
 *  Status [`PpStatus::Err`] is reserved for cases where validation
 *  could not run at all (e.g. a typed-mismatch handle).
 *
 *  Both handles must outlive the call. Common failure modes are
 *  [`PpStatus::InvalidHandle`] and [`PpStatus::TypeMismatch`].
 */
int32_t
pp_schema_validate (
    uint32_t schema_handle,
    uint32_t proto_handle,
    Vec_uint8_t * out_messages);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_PANPROTO_C__ */
