{-# LANGUAGE ForeignFunctionInterface #-}

-- | Raw @foreign import@ declarations for @libpanproto_c@.
--
-- Direct callers should prefer "Panproto.Rust.Handle"; this module is
-- the unsafe layer. Every entrypoint here matches a function in
-- @cbits\/panproto.h@ generated by @safer-ffi@, or the small pointer-
-- based glue layer in @cbits\/panproto_glue.c@.
--
-- The glue layer exists because GHC\'s @CApiFFI@ does not reliably
-- pass structs by value across all platforms. The glue functions
-- ('pp_protocol_define_at', 'pp_buf_free_at') accept pointers and
-- forward to the by-value Rust API.
--
-- All entrypoints are imported as @safe@: panproto-c calls may
-- allocate, release, or take non-trivial CPU time, so suppressing
-- the GHC RTS\'s safe-call shim would risk preventing GC during the
-- call. The exceptions are 'pp_handle_free' and 'pp_buf_free_at',
-- which are short and side-effecting; they remain @safe@ for
-- uniformity and because the cost is negligible at the rates these
-- are called.
module Panproto.Rust.FFI
    ( -- * Storable types
      VecU8 (..)

      -- * Lifecycle
    , pp_init
    , pp_handle_free
    , pp_buf_free_at

      -- * Errors
    , pp_last_error_take

      -- * Protocol
    , pp_protocol_define_at
    , pp_protocol_serialize
    ) where

import Data.Word (Word32, Word8)
import Foreign.C.Types (CInt (..), CSize (..))
import Foreign.Ptr (Ptr)
import Foreign.Storable (Storable (..))

#include "panproto.h"

-- | Mirror of @safer_ffi::repr_c::Vec\<u8\>@. Holds an owning heap
-- pointer plus length and capacity. Ownership transfers across the
-- FFI boundary on out-params, and the caller releases it with
-- 'pp_buf_free_at'.
data VecU8 = VecU8
    { vecPtr :: !(Ptr Word8)
    , vecLen :: !CSize
    , vecCap :: !CSize
    }
    deriving stock (Eq, Show)

instance Storable VecU8 where
    sizeOf _ = #size Vec_uint8_t
    alignment _ = #alignment Vec_uint8_t
    peek p = do
        ptr <- (#peek Vec_uint8_t, ptr) p
        len <- (#peek Vec_uint8_t, len) p
        cap <- (#peek Vec_uint8_t, cap) p
        pure (VecU8 ptr len cap)
    poke p VecU8 {vecPtr, vecLen, vecCap} = do
        (#poke Vec_uint8_t, ptr) p vecPtr
        (#poke Vec_uint8_t, len) p vecLen
        (#poke Vec_uint8_t, cap) p vecCap

-- | Initialize the panproto-c runtime. Always returns @PpStatus::Ok@.
foreign import ccall safe "pp_init"
    pp_init :: IO CInt

-- | Free a handle's slab slot. Safe to call on freed handles.
foreign import ccall safe "pp_handle_free"
    pp_handle_free :: Word32 -> IO CInt

-- | Free a 'VecU8' returned by panproto-c. Wraps the by-value
-- @pp_buf_free@ exposed by Rust; the glue zeros the storage on
-- behalf of the Haskell caller so a stale 'VecU8' record cannot be
-- double-freed.
foreign import ccall safe "pp_buf_free_at"
    pp_buf_free_at :: Ptr VecU8 -> IO ()

-- | Take the last error envelope as CBOR bytes. On success, the
-- 'VecU8' out-param is populated and must be freed via 'pp_buf_free_at'.
foreign import ccall safe "pp_last_error_take"
    pp_last_error_take :: Ptr VecU8 -> IO CInt

-- | Ingest a CBOR-encoded @Protocol@ specification via a pointer-and-
-- length pair (no by-value struct on the FFI signature).
foreign import ccall safe "pp_protocol_define_at"
    pp_protocol_define_at :: Ptr Word8 -> CSize -> Ptr Word32 -> IO CInt

-- | Serialize the protocol referenced by the handle to CBOR.
foreign import ccall safe "pp_protocol_serialize"
    pp_protocol_serialize :: Word32 -> Ptr VecU8 -> IO CInt
