#![allow(
    missing_docs,
    clippy::uninlined_format_args,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::format_push_string,
    clippy::single_char_add_str
)]

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct GrammarSpec {
    extensions: Vec<String>,
    #[serde(default)]
    c_symbol: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    directory: Option<String>,
    #[allow(dead_code)]
    repo: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();
    let grammars_toml_path = workspace_root.join("grammars.toml");
    let grammars_dir = workspace_root.join("grammars");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!(
        "cargo:rerun-if-changed={}",
        grammars_toml_path.display()
    );

    let toml_str = fs::read_to_string(&grammars_toml_path)
        .expect("failed to read grammars.toml");
    let manifest: BTreeMap<String, GrammarSpec> =
        toml::from_str(&toml_str).expect("failed to parse grammars.toml");

    let mut enabled: Vec<(String, GrammarSpec)> = Vec::new();

    for (name, spec) in manifest {
        let feature_env = format!(
            "CARGO_FEATURE_LANG_{}",
            name.to_uppercase().replace('-', "_")
        );
        if env::var(&feature_env).is_ok() {
            enabled.push((name, spec));
        }
    }

    // Compile C sources for each enabled grammar.
    for (name, spec) in &enabled {
        let lang_dir = grammars_dir.join(name).join("src");
        if !lang_dir.exists() {
            println!(
                "cargo:warning=Grammar '{}' sources not found at {}; run tools/fetch-grammars.py",
                name,
                lang_dir.display()
            );
            continue;
        }

        compile_grammar(name, spec, &lang_dir);
    }

    // Generate the Rust binding file.
    let generated = generate_rust_bindings(&enabled, &grammars_dir);
    let out_file = out_dir.join("grammar_table.rs");
    fs::write(&out_file, generated).expect("failed to write grammar_table.rs");
}

fn compile_grammar(name: &str, spec: &GrammarSpec, src_dir: &Path) {
    let c_symbol = spec
        .c_symbol
        .as_deref()
        .unwrap_or(name);
    let parser_c = src_dir.join("parser.c");
    let scanner_c = src_dir.join("scanner.c");
    let scanner_cc = src_dir.join("scanner.cc");

    if !parser_c.exists() {
        println!("cargo:warning=Grammar '{name}': no parser.c found");
        return;
    }

    println!("cargo:rerun-if-changed={}", parser_c.display());

    // Compile parser.c (and scanner.c if present).
    let mut build = cc::Build::new();
    build
        .file(&parser_c)
        .include(src_dir)
        .std("c11")
        .warnings(false);

    // Add common/ directory as include path (for grammars like PHP).
    let common_dir = src_dir.join("common");
    if common_dir.is_dir() {
        build.include(&common_dir);
    }

    if scanner_c.exists() {
        build.file(&scanner_c);
        println!("cargo:rerun-if-changed={}", scanner_c.display());
    }

    // Use a unique output name to avoid collisions.
    build.compile(&format!("tree_sitter_{c_symbol}"));

    // Compile C++ scanner separately if present.
    if scanner_cc.exists() {
        println!("cargo:rerun-if-changed={}", scanner_cc.display());

        cc::Build::new()
            .cpp(true)
            .file(&scanner_cc)
            .include(src_dir)
            .std("c++14")
            .warnings(false)
            .compile(&format!("tree_sitter_{c_symbol}_scanner"));
    }
}

fn generate_rust_bindings(
    enabled: &[(String, GrammarSpec)],
    grammars_dir: &Path,
) -> String {
    let mut code = String::new();

    code.push_str("// Auto-generated by build.rs. Do not edit.\n\n");

    // Extern declarations and node-types includes.
    code.push_str("unsafe extern \"C\" {\n");
    let mut available: Vec<(&String, &GrammarSpec)> = Vec::new();
    for (name, spec) in enabled {
        let c_symbol = spec.c_symbol.as_deref().unwrap_or(name);
        let lang_dir = grammars_dir.join(name).join("src");

        if !lang_dir.join("parser.c").exists() {
            continue;
        }

        code.push_str(&format!(
            "    fn tree_sitter_{c_symbol}() -> *const ();\n"
        ));
        available.push((name, spec));
    }
    code.push_str("}\n\n");

    for (name, _spec) in &available {
        let lang_dir = grammars_dir.join(name).join("src");
        let node_types_path = lang_dir.join("node-types.json");
        let abs_path = node_types_path
            .canonicalize()
            .unwrap_or_else(|_| node_types_path.clone());
        let const_name = name.to_uppercase().replace('-', "_");
        code.push_str(&format!(
            "const {const_name}_NODE_TYPES: &[u8] = include_bytes!(\"{}\");\n",
            abs_path.display(),
        ));
    }

    code.push_str("\n");

    // GrammarEntry struct using a raw pointer to the language function.
    code.push_str("pub(crate) struct GrammarEntry {\n");
    code.push_str("    pub name: &'static str,\n");
    code.push_str("    pub extensions: &'static [&'static str],\n");
    code.push_str("    pub language_fn_ptr: *const (),\n");
    code.push_str("    pub node_types: &'static [u8],\n");
    code.push_str("}\n\n");
    code.push_str("unsafe impl Send for GrammarEntry {}\n");
    code.push_str("unsafe impl Sync for GrammarEntry {}\n");

    code.push_str("\npub(crate) fn enabled_grammars() -> Vec<GrammarEntry> {\n");
    code.push_str("    let mut grammars = Vec::new();\n");

    for (name, spec) in &available {
        let c_symbol = spec.c_symbol.as_deref().unwrap_or(name);

        let exts: Vec<String> = spec
            .extensions
            .iter()
            .map(|e| format!("\"{}\"", e))
            .collect();
        let exts_str = exts.join(", ");
        let const_name = name.to_uppercase().replace('-', "_");

        code.push_str(&format!(
            "    grammars.push(GrammarEntry {{\n\
             \x20       name: \"{name}\",\n\
             \x20       extensions: &[{exts_str}],\n\
             \x20       language_fn_ptr: tree_sitter_{c_symbol} as *const (),\n\
             \x20       node_types: {const_name}_NODE_TYPES,\n\
             \x20   }});\n"
        ));
    }

    code.push_str("    grammars\n}\n");

    // Extension-to-language lookup.
    code.push_str(
        "\npub(crate) fn ext_to_lang(ext: &str) -> Option<&'static str> {\n\
         \x20   match ext {\n",
    );

    // Build extension map (first-registered wins for conflicts).
    let mut ext_map: BTreeMap<String, String> = BTreeMap::new();
    for (name, spec) in enabled {
        let lang_dir = grammars_dir.join(name).join("src");
        if !lang_dir.join("parser.c").exists() {
            continue;
        }
        for ext in &spec.extensions {
            ext_map.entry(ext.clone()).or_insert_with(|| name.clone());
        }
    }

    for (ext, lang) in &ext_map {
        code.push_str(&format!(
            "        \"{}\" => Some(\"{}\"),\n",
            ext, lang
        ));
    }

    code.push_str("        _ => None,\n    }\n}\n");

    code
}
