/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_PANPROTO_C__
#define __RUST_PANPROTO_C__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {
    /** <No documentation available> */
    uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_uint8_t;

/** \brief
 *  Free a byte buffer returned by panproto-c.
 *
 *  The host must call this on every `repr_c::Vec<u8>` it receives, or
 *  memory leaks. Calling twice is undefined; do not double-free.
 */
void
pp_buf_free (
    Vec_uint8_t buf);

/** \brief
 *  Free a handle, marking its slab slot reusable.
 *
 *  Double-free is safe: a freed slot stays freed.
 */
int32_t
pp_handle_free (
    uint32_t handle);

/** \brief
 *  Initialize the panproto-c runtime.
 *
 *  Currently a no-op: the slab and last-error slots are thread-local
 *  `RefCell`s that initialize lazily. Reserved for future panic-hook
 *  installation or registry warm-up. Always returns [`PpStatus::Ok`].
 */
int32_t
pp_init (void);

/** \brief
 *  Take the last error envelope as a CBOR byte vector.
 *
 *  On `PpStatus::Ok`, `out` is populated with the freshly allocated
 *  bytes; the host must release them via [`pp_buf_free`]. If no error
 *  is pending, `out` receives an empty buffer and the status is
 *  [`PpStatus::Ok`].
 */
int32_t
pp_last_error_take (
    Vec_uint8_t * out);

/** \brief
 *  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_ref_uint8 {
    /** \brief
     *  Pointer to the first element (if any).
     */
    uint8_t const * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_ref_uint8_t;

/** \brief
 *  Ingest a CBOR-encoded [`Protocol`] specification and register it
 *  in the slab.
 *
 *  On success, `out_handle` is set to a fresh handle and [`PpStatus::Ok`]
 *  is returned. On CBOR decode failure, [`PpStatus::Serialization`] is
 *  returned and `out_handle` is left untouched.
 */
int32_t
pp_protocol_define (
    slice_ref_uint8_t spec,
    uint32_t * out_handle);

/** \brief
 *  Serialize the protocol referenced by `proto` to CBOR.
 *
 *  On success, `out` is populated with freshly allocated CBOR bytes;
 *  the host must release them via `pp_buf_free`. Common failure modes
 *  are [`PpStatus::InvalidHandle`] and [`PpStatus::TypeMismatch`].
 */
int32_t
pp_protocol_serialize (
    uint32_t proto,
    Vec_uint8_t * out);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_PANPROTO_C__ */
