"""Type stubs for the ``panproto._native`` extension module.

Hand-written; covers the surface that downstream Python consumers
exercise. Methods/classes not yet stubbed fall back via the
implicit-reexport in ``__init__.py``; extending this file is preferred
over per-callsite ``# type: ignore``.
"""

from collections.abc import Iterable, Mapping, Sequence
from os import PathLike
from typing import Self

type JsonValue = str | int | float | bool | None | list[JsonValue] | dict[str, JsonValue]

# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------

class PanprotoError(Exception): ...
class CheckError(PanprotoError): ...
class ExistenceCheckError(PanprotoError): ...
class ExprError(PanprotoError): ...
class GatError(PanprotoError): ...
class IoError(PanprotoError): ...
class LensError(PanprotoError): ...
class MigrationError(PanprotoError): ...
class SchemaValidationError(PanprotoError): ...
class VcsError(PanprotoError): ...
class ProjectError(PanprotoError): ...
class GitBridgeError(PanprotoError): ...

# ---------------------------------------------------------------------------
# Schema graph
# ---------------------------------------------------------------------------

class Vertex:
    id: str
    kind: str
    nsid: str | None
    def to_dict(self) -> dict[str, JsonValue]: ...

class Edge:
    src: str
    tgt: str
    kind: str
    name: str | None
    def to_dict(self) -> dict[str, JsonValue]: ...

class HyperEdge:
    id: str
    kind: str
    signature: dict[str, str]
    parent_label: str
    def to_dict(self) -> dict[str, JsonValue]: ...

class Constraint:
    sort: str
    value: str

class Complement:
    @property
    def dropped_node_count(self) -> int: ...
    @property
    def dropped_arc_count(self) -> int: ...
    def to_dict(self) -> dict[str, JsonValue]: ...

class SchemaBuilder:
    def vertex(self, id: str, kind: str, nsid: str | None = ..., /) -> None: ...
    def edge(
        self,
        src: str,
        tgt: str,
        kind: str,
        name: str | None = ...,
    ) -> None: ...
    def hyper_edge(
        self,
        id: str,
        kind: str,
        signature: dict[str, str],
        parent: str,
    ) -> None: ...
    def constraint(self, vertex_id: str, sort: str, value: str) -> None: ...
    def build(self) -> Schema: ...

class Schema:
    vertex_count: int
    edge_count: int
    vertices: list[Vertex]
    edges: list[Edge]
    hyper_edges: list[HyperEdge]
    protocol: str
    def vertex(self, name: str) -> Vertex | None: ...
    def has_vertex(self, name: str) -> bool: ...
    def constraints_for(self, vertex: str) -> list[Constraint]: ...
    def field_text(self, vertex: str, field_name: str) -> str | None: ...
    def incoming_edges(self, vertex: str) -> list[Edge]: ...
    def outgoing_edges(self, vertex: str) -> list[Edge]: ...
    def normalize(self) -> Schema: ...
    def validate(self, protocol: Protocol) -> list[str]: ...
    def to_dict(self) -> dict[str, JsonValue]: ...
    def to_json(self) -> str: ...
    def theory(self, name: str | None = ...) -> Theory: ...
    @staticmethod
    def from_json(json: str) -> Schema: ...
    @staticmethod
    def from_atproto_lexicon(doc: Mapping[str, JsonValue] | str) -> Schema: ...

# ---------------------------------------------------------------------------
# Protocol registry
# ---------------------------------------------------------------------------

class Protocol:
    name: str
    schema_theory: str
    instance_theory: str
    obj_kinds: list[str]
    constraint_sorts: list[str]
    edge_rules: list[dict[str, JsonValue]]
    def schema(self) -> SchemaBuilder: ...
    def to_dict(self) -> dict[str, JsonValue]: ...
    @classmethod
    def from_theories(
        cls,
        name: str,
        schema_theory: Theory | str,
        instance_theory: Theory | str | None = ...,
        obj_kinds: Sequence[str] | None = ...,
        edge_rules: Sequence[dict[str, JsonValue]] | None = ...,
        constraint_sorts: Sequence[str] | None = ...,
        has_order: bool = ...,
        has_coproducts: bool = ...,
        has_recursion: bool = ...,
        has_causal: bool = ...,
        nominal_identity: bool = ...,
        has_defaults: bool = ...,
        has_coercions: bool = ...,
        has_mergers: bool = ...,
        has_policies: bool = ...,
    ) -> Protocol: ...

def define_protocol(spec: Mapping[str, JsonValue]) -> Protocol: ...
def get_builtin_protocol(name: str) -> Protocol: ...
def list_builtin_protocols() -> list[str]: ...

# ---------------------------------------------------------------------------
# GAT theories
# ---------------------------------------------------------------------------

class Theory:
    name: str
    sorts: list[dict[str, JsonValue]]
    ops: list[dict[str, JsonValue]]
    eqs: list[dict[str, JsonValue]]
    sort_count: int
    op_count: int
    eq_count: int
    def to_dict(self) -> dict[str, JsonValue]: ...
    def to_json(self) -> str: ...
    def to_yaml(self) -> str: ...
    @classmethod
    def from_dict_json(cls, payload: str) -> Theory: ...
    @classmethod
    def from_dict_yaml(cls, payload: str) -> Theory: ...
    @classmethod
    def from_json(cls, source: str) -> Theory: ...
    @classmethod
    def from_yaml(cls, source: str) -> Theory: ...
    @classmethod
    def from_nickel(
        cls,
        source: str,
        import_paths: Sequence[str | PathLike[str]] | None = ...,
    ) -> Theory: ...
    @classmethod
    def from_path(cls, path: str | PathLike[str]) -> Theory: ...

class TheoryBuilder:
    def __init__(self, name: str) -> None: ...
    def sort(self, name: str) -> Self: ...
    def op(
        self,
        name: str,
        inputs: Sequence[str],
        output: str,
        input_names: Sequence[str] | None = ...,
    ) -> Self: ...
    def eq(self, name: str, lhs: str, rhs: str) -> Self: ...
    def build(self) -> Theory: ...

class Model:
    theory_name: str
    sort_interp_keys: list[str]

def create_theory(spec: Mapping[str, JsonValue]) -> Theory: ...
def colimit_theories(t1: Theory, t2: Theory, shared: Theory, /) -> Theory: ...
def free_model(
    theory: Theory, /, max_depth: int = ..., max_terms_per_sort: int = ...
) -> Model: ...
def check_model(model: Model, theory: Theory) -> list[str]: ...
def check_morphism(
    morphism: Mapping[str, JsonValue], domain: Theory, codomain: Theory
) -> None: ...
def migrate_model(morphism: Mapping[str, JsonValue], model: Model) -> Model: ...

# ---------------------------------------------------------------------------
# Lexicon / schema-document parsing
# ---------------------------------------------------------------------------

def parse_atproto_lexicon(doc: Mapping[str, JsonValue] | str) -> Schema: ...
def parse_schema_document(
    protocol: str, doc: Mapping[str, JsonValue] | str
) -> Schema: ...
def parse_schema_bundle(
    protocol: str, docs: Sequence[Mapping[str, JsonValue] | str]
) -> Schema: ...
def theory_of(schema: Schema, name: str | None = ...) -> Theory: ...

# ---------------------------------------------------------------------------
# Migration
# ---------------------------------------------------------------------------

class Migration:
    def to_dict(self) -> dict[str, JsonValue]: ...
    @staticmethod
    def from_dict(spec: Mapping[str, JsonValue]) -> Migration: ...

class CompiledMigration:
    def lift(self, instance: Instance, /) -> Instance: ...
    def get(self, instance: Instance, /) -> tuple[Instance, Complement]: ...
    def put(self, view: Instance, complement: Complement, /) -> Instance: ...
    def to_lens(self) -> Lens: ...
    def check_laws(self, instance: Instance, /) -> None: ...
    def check_get_put(self, instance: Instance, /) -> None: ...
    def check_put_get(self, instance: Instance, /) -> None: ...
    def to_dict(self) -> dict[str, JsonValue]: ...

class MigrationBuilder:
    def __init__(self) -> None: ...
    def map_vertex(self, src: str, tgt: str) -> None: ...
    def resolve(
        self,
        src_vertex: str,
        tgt_vertex: str,
        edge_src: str,
        edge_tgt: str,
        edge_kind: str,
        edge_name: str | None = ...,
    ) -> None: ...
    def build(self) -> Migration: ...

def compile_migration(
    migration: Migration, src_schema: Schema, tgt_schema: Schema
) -> CompiledMigration: ...
def check_existence(
    migration: Migration,
    protocol: Protocol,
    src_schema: Schema,
    tgt_schema: Schema,
) -> dict[str, JsonValue]: ...
def compose_migrations(mig1: Migration, mig2: Migration) -> Migration: ...
def invert_migration(
    migration: Migration, src_schema: Schema, tgt_schema: Schema
) -> Migration: ...
def check_coverage(
    compiled: CompiledMigration,
    instances: list[Instance],
    src_schema: Schema,
    tgt_schema: Schema,
) -> dict[str, JsonValue]: ...

# ---------------------------------------------------------------------------
# Hom search + cascade
# ---------------------------------------------------------------------------

class TheoryMorphism:
    name: str
    domain: str
    codomain: str
    sort_map: dict[str, str]
    op_map: dict[str, str]
    def to_dict(self) -> dict[str, JsonValue]: ...
    @staticmethod
    def from_dict(spec: Mapping[str, JsonValue]) -> TheoryMorphism: ...

class SchemaMorphism:
    name: str
    src_protocol: str
    tgt_protocol: str
    vertex_map: dict[str, str]
    def to_dict(self) -> dict[str, JsonValue]: ...

class FoundMorphism:
    vertex_map: dict[str, str]
    quality: float
    def to_migration(self) -> Migration: ...
    def to_dict(self) -> dict[str, JsonValue]: ...

def find_morphisms(
    src: Schema,
    tgt: Schema,
    anchors: dict[str, str] | None = ...,
    monic: bool = ...,
    epic: bool = ...,
    iso: bool = ...,
    max_results: int = ...,
    relax_edge_name_pruning: bool = ...,
) -> list[FoundMorphism]: ...
def find_best_morphism(
    src: Schema,
    tgt: Schema,
    anchors: dict[str, str] | None = ...,
    monic: bool = ...,
    epic: bool = ...,
    iso: bool = ...,
    relax_edge_name_pruning: bool = ...,
) -> FoundMorphism | None: ...
def induce_schema_morphism(
    theory_morph: TheoryMorphism, src_schema: Schema
) -> SchemaMorphism: ...
def induce_migration_from_theory(
    theory_morph: TheoryMorphism, src_schema: Schema, tgt_schema: Schema
) -> tuple[SchemaMorphism, CompiledMigration]: ...

# ---------------------------------------------------------------------------
# Diff / classification
# ---------------------------------------------------------------------------

class CompatReport:
    compatible: bool
    breaking: list[str]
    def to_dict(self) -> dict[str, JsonValue]: ...

class SchemaDiff:
    added_vertices: list[str]
    removed_vertices: list[str]
    def to_dict(self) -> dict[str, JsonValue]: ...

def diff_schemas(old: Schema, new: Schema, /) -> SchemaDiff: ...
def diff_and_classify(
    old: Schema, new: Schema, protocol: Protocol, /
) -> CompatReport: ...

# ---------------------------------------------------------------------------
# Instance + I/O
# ---------------------------------------------------------------------------

class Instance:
    root: int
    node_count: int
    arc_count: int
    def validate(self) -> list[str]: ...
    def to_dict(self) -> dict[str, JsonValue]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(schema: Schema, root_vertex: str, payload: str) -> Instance: ...

class IoRegistry:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def list_protocols(self) -> Iterable[str]: ...
    def emit(self, protocol: str, schema: Schema, instance: Instance) -> bytes: ...
    def parse(self, protocol: str, schema: Schema, data: bytes) -> Instance: ...

# ---------------------------------------------------------------------------
# Lens + protolens chain
# ---------------------------------------------------------------------------

class Lens:
    def get(self, instance: Instance, /) -> tuple[Instance, Complement]: ...
    def put(self, view: Instance, complement: Complement, /) -> Instance: ...
    def compose(self, other: Lens, /) -> Lens: ...
    def check_get_put(self, instance: Instance) -> None: ...
    def check_put_get(self, instance: Instance) -> None: ...
    def check_laws(self, instance: Instance) -> None: ...

class ProtolensChain:
    def to_json(self) -> str: ...
    def compose(self, other: ProtolensChain, /) -> ProtolensChain: ...
    def fuse(self) -> ProtolensChain: ...
    def instantiate(self, schema: Schema, protocol: Protocol, /) -> Lens: ...
    @classmethod
    def from_json(cls, payload: str) -> ProtolensChain: ...
    @staticmethod
    def from_dsl_json(source: str, body_vertex: str) -> ProtolensChain: ...
    @staticmethod
    def from_dsl_yaml(source: str, body_vertex: str) -> ProtolensChain: ...
    @staticmethod
    def from_dsl_nickel(
        source: str,
        body_vertex: str,
        import_paths: Sequence[str | PathLike[str]] | None = ...,
    ) -> ProtolensChain: ...
    @staticmethod
    def from_dsl_path(
        path: str | PathLike[str], body_vertex: str
    ) -> ProtolensChain: ...
    @staticmethod
    def auto_generate(
        src: Schema,
        tgt: Schema,
        protocol: Protocol,
        stringency: str | None = ...,
    ) -> ProtolensChain: ...
    @staticmethod
    def auto_generate_with_hints(
        src_schema: Schema,
        tgt_schema: Schema,
        protocol: Protocol,
        hints: dict[str, str],
        stringency: str | None = ...,
    ) -> ProtolensChain: ...
    @staticmethod
    def auto_generate_with_hint_spec(
        src_schema: Schema,
        tgt_schema: Schema,
        protocol: Protocol,
        hints: str,
    ) -> ProtolensChain: ...

def auto_generate_lens(
    src: Schema,
    tgt: Schema,
    protocol: Protocol,
    stringency: str | None = ...,
) -> tuple[Lens, float, list[dict[str, JsonValue]]]: ...
def auto_generate_lens_candidates(
    src_schema: Schema,
    tgt_schema: Schema,
    protocol: Protocol,
    top_n: int = ...,
    stringency: str | None = ...,
) -> list[dict[str, JsonValue]]: ...

# ---------------------------------------------------------------------------
# Expressions
# ---------------------------------------------------------------------------

class Expr:
    def to_dict(self) -> dict[str, JsonValue]: ...

def parse_expr(text: str) -> Expr: ...
def pretty_print_expr(expr: Expr) -> str: ...

# ---------------------------------------------------------------------------
# VCS
# ---------------------------------------------------------------------------

class BisectState:
    def to_dict(self) -> dict[str, JsonValue]: ...

class Repository:
    @classmethod
    def init(cls, path: str | PathLike[str]) -> Repository: ...
    @classmethod
    def open(cls, path: str | PathLike[str]) -> Repository: ...
    @property
    def working_dir(self) -> str: ...
    def head(self) -> str | None: ...
    def head_state(self) -> str: ...
    def has_staged(self) -> bool: ...
    def list_branches(self) -> list[tuple[str, str]]: ...
    def list_tags(self) -> list[tuple[str, str]]: ...
    def log(self) -> list[dict[str, JsonValue]]: ...
    def index(self) -> list[dict[str, JsonValue]]: ...
    def add(self, target: Schema, /) -> None: ...
    def add_data(self, path: str, key: str | None = None) -> dict[str, JsonValue]: ...
    def commit(self, message: str, author: str, *, skip_verify: bool = ...) -> str: ...
    def amend(self, message: str, author: str) -> str: ...
    def reset(self, target: str, mode: str, author: str) -> None: ...
    def clear_index(self) -> None: ...
    def resolve_ref(self, name: str) -> str | None: ...
    def schema_at(self, ref: str) -> Schema: ...
    def data_at(self, ref: str) -> list[dict[str, str | bytes | int | None]]: ...
    def create_branch(self, name: str, commit_id: str) -> None: ...
    def create_and_checkout_branch(self, name: str, commit_id: str) -> None: ...
    def checkout_branch(self, name: str) -> None: ...
    def checkout_detached(self, ref: str) -> None: ...
    def delete_branch(self, name: str) -> None: ...
    def force_delete_branch(self, name: str) -> None: ...
    def rename_branch(self, old: str, new: str) -> None: ...
    def create_tag(self, name: str, commit_id: str) -> None: ...
    def create_tag_force(self, name: str, commit_id: str) -> None: ...
    def create_annotated_tag(
        self, name: str, commit_id: str, author: str, message: str
    ) -> str: ...
    def read_annotated_tag(self, name: str) -> dict[str, JsonValue]: ...
    def delete_tag(self, name: str) -> None: ...
    def merge(self, branch: str, author: str) -> dict[str, JsonValue]: ...
    def rebase(self, onto: str, author: str) -> str: ...
    def cherry_pick(self, ref: str) -> str: ...
    def bisect_start(self, good: str, bad: str) -> tuple[BisectState, dict[str, JsonValue]]: ...
    def stash_push(
        self, schema_id: str, author: str, message: str | None = ...
    ) -> str: ...
    def stash_pop(self) -> str: ...
    def stash_apply(self, index: int) -> str: ...
    def stash_drop(self, ref: str) -> None: ...
    def stash_clear(self) -> None: ...
    def stash_list(self) -> list[dict[str, JsonValue]]: ...
    def stash_show(self, ref: str) -> dict[str, JsonValue]: ...
    def read_reflog(self, ref: str) -> list[dict[str, JsonValue]]: ...
    def detect_staleness(self) -> dict[str, JsonValue]: ...
    def encode_edit_log_empty(self) -> bytes: ...
    def gc(self) -> None: ...
    def blame_vertex(self, head: str, vertex_id: str) -> dict[str, JsonValue]: ...
    def blame_edge(
        self, head: str, src: str, tgt: str, kind: str, name: str | None = ...
    ) -> dict[str, JsonValue]: ...
    def blame_constraint(self, head: str, vertex_id: str, sort: str) -> dict[str, JsonValue]: ...

class VcsRepository(Repository): ...

# ---------------------------------------------------------------------------
# Parse + ParseEmitLens
# ---------------------------------------------------------------------------

class ParseEmitLens:
    def parse(self, source: bytes) -> Schema: ...
    def emit(self, schema: Schema) -> bytes: ...
    @staticmethod
    def check_emit_parse(schema: Schema) -> str | None: ...
    @staticmethod
    def check_parse_emit(bytes_: bytes) -> str | None: ...
    @staticmethod
    def strip_complement(schema: Schema) -> Schema: ...
    @staticmethod
    def kind_multiset(schema: Schema) -> dict[str, int]: ...

class AstParserRegistry:
    def __init__(
        self, extra_grammars: Sequence[Mapping[str, str | int | None]] | None = ...
    ) -> None: ...
    def protocol_names(self) -> list[str]: ...
    def detect_language(self, path: str) -> str | None: ...
    def parse_with_protocol(
        self, protocol: str, content: bytes, file_path: str = ...
    ) -> Schema: ...
    def parse_file(self, path: str, content: bytes) -> Schema: ...
    def emit(self, protocol: str, schema: Schema) -> bytes: ...
    def emit_pretty(self, protocol: str, schema: Schema) -> bytes: ...
    def lens(self, protocol: str) -> ParseEmitLens: ...
    def override_grammar(
        self,
        name: str,
        extensions: Sequence[str],
        language_ptr: int,
        node_types: bytes,
        tags_query: str | None = ...,
        grammar_json: bytes | None = ...,
    ) -> None: ...

def available_grammars() -> list[str]: ...
def parse_source_file(path: str, content: bytes) -> Schema: ...

# ---------------------------------------------------------------------------
# Project / git bridge surface
# ---------------------------------------------------------------------------

class ProjectBuilder:
    def build(self) -> ProjectSchema: ...

class ProjectSchema:
    def to_dict(self) -> dict[str, JsonValue]: ...

class GitImportResult:
    def to_dict(self) -> dict[str, JsonValue]: ...
