"""Type stubs for the ``panproto._native`` extension module.

Hand-written; covers the surface that downstream Python consumers
(``didactic`` and friends) exercise. Methods/classes not yet stubbed
fall back to ``Any`` via the implicit-reexport in ``__init__.py``;
extending this file is preferred over per-callsite ``# type: ignore``.

Notes
-----
Argument and return types are best-effort and reflect runtime behaviour
of the pyo3 wrapper, not the underlying Rust signatures. Where the
runtime returns a heterogeneous payload (e.g. ``Schema.to_dict`` →
nested ``dict``), the stub uses ``dict[str, object]`` rather than a
narrower union; widen as needed when a caller demands stricter types.
"""

from collections.abc import Iterable, Mapping, Sequence
from os import PathLike
from typing import Self

# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------

class PanprotoError(Exception): ...
class CheckError(PanprotoError): ...
class ExistenceCheckError(PanprotoError): ...
class ExprError(PanprotoError): ...
class GatError(PanprotoError): ...
class IoError(PanprotoError): ...
class LensError(PanprotoError): ...
class MigrationError(PanprotoError): ...
class SchemaValidationError(PanprotoError): ...
class VcsError(PanprotoError): ...
class ProjectError(PanprotoError): ...
class GitBridgeError(PanprotoError): ...

# ---------------------------------------------------------------------------
# Schema graph
# ---------------------------------------------------------------------------

class Vertex:
    name: str
    kind: str
    def to_dict(self) -> dict[str, object]: ...

class Edge:
    name: str
    source: str
    target: str
    def to_dict(self) -> dict[str, object]: ...

class HyperEdge:
    name: str
    def to_dict(self) -> dict[str, object]: ...

class Constraint:
    name: str
    def to_dict(self) -> dict[str, object]: ...

class Complement:
    def to_dict(self) -> dict[str, object]: ...

class SchemaBuilder:
    def vertex(self, name: str, kind: str) -> Self: ...
    def edge(
        self,
        name: str,
        source: str,
        target: str,
        *,
        cardinality: str | None = ...,
    ) -> Self: ...
    def hyper_edge(self, name: str, /, *args: object, **kwargs: object) -> Self: ...
    def constraint(self, name: str, /, *args: object, **kwargs: object) -> Self: ...
    def build(self) -> Schema: ...

class Schema:
    def vertex_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def vertices(self) -> list[Vertex]: ...
    def edges(self) -> list[Edge]: ...
    def hyper_edges(self) -> list[HyperEdge]: ...
    def vertex(self, name: str) -> Vertex | None: ...
    def has_vertex(self, name: str) -> bool: ...
    def constraints_for(self, vertex: str) -> list[Constraint]: ...
    def incoming_edges(self, vertex: str) -> list[Edge]: ...
    def outgoing_edges(self, vertex: str) -> list[Edge]: ...
    def protocol(self) -> Protocol: ...
    def normalize(self) -> Schema: ...
    def validate(self) -> None: ...
    def to_dict(self) -> dict[str, object]: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, payload: str) -> Schema: ...

# ---------------------------------------------------------------------------
# Protocol registry
# ---------------------------------------------------------------------------

class Protocol:
    def name(self) -> str: ...
    def schema(self) -> SchemaBuilder: ...
    def schema_theory(self) -> Theory: ...
    def instance_theory(self) -> Theory: ...
    def obj_kinds(self) -> list[str]: ...
    def constraint_sorts(self) -> list[str]: ...
    def edge_rules(self) -> list[dict[str, object]]: ...
    def to_dict(self) -> dict[str, object]: ...
    @classmethod
    def from_theories(
        cls,
        *,
        name: str,
        schema_theory: Theory,
        obj_kinds: Sequence[str],
        instance_theory: Theory | None = ...,
    ) -> Protocol: ...

def define_protocol(*args: object, **kwargs: object) -> Protocol: ...
def get_builtin_protocol(name: str) -> Protocol: ...
def list_builtin_protocols() -> list[str]: ...

# ---------------------------------------------------------------------------
# GAT theories
# ---------------------------------------------------------------------------

class Theory:
    def name(self) -> str: ...
    def sorts(self) -> list[str]: ...
    def ops(self) -> list[dict[str, object]]: ...
    def eqs(self) -> list[dict[str, object]]: ...
    def sort_count(self) -> int: ...
    def op_count(self) -> int: ...
    def eq_count(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_dict_json(cls, payload: str) -> Theory: ...
    @classmethod
    def from_json(cls, source: str) -> Theory: ...
    @classmethod
    def from_yaml(cls, source: str) -> Theory: ...
    @classmethod
    def from_nickel(
        cls,
        source: str,
        import_paths: Sequence[str | PathLike[str]] | None = ...,
    ) -> Theory: ...
    @classmethod
    def from_path(cls, path: str | PathLike[str]) -> Theory: ...

class TheoryBuilder:
    def __init__(self, name: str) -> None: ...
    def sort(self, name: str) -> Self: ...
    def op(
        self,
        name: str,
        inputs: Sequence[str],
        output: str,
        input_names: Sequence[str] | None = ...,
    ) -> Self: ...
    def eq(self, name: str, lhs: str, rhs: str) -> Self: ...
    def build(self) -> Theory: ...

class Model:
    def theory_name(self) -> str: ...
    def sort_interp_keys(self) -> list[str]: ...

def create_theory(spec: Mapping[str, object]) -> Theory: ...
def colimit_theories(t1: Theory, t2: Theory, shared: Theory, /) -> Theory: ...
def free_model(theory: Theory, /) -> Model: ...
def check_model(model: Model, /) -> None: ...
def check_morphism(*args: object, **kwargs: object) -> None: ...
def migrate_model(*args: object, **kwargs: object) -> Model: ...

# ---------------------------------------------------------------------------
# Migration
# ---------------------------------------------------------------------------

class Migration:
    def to_dict(self) -> dict[str, object]: ...

class CompiledMigration:
    def apply(self, instance: Instance, /) -> Instance: ...

class MigrationBuilder:
    def build(self) -> Migration: ...

def add_field(*args: object, **kwargs: object) -> Migration: ...
def remove_field(*args: object, **kwargs: object) -> Migration: ...
def rename_field(*args: object, **kwargs: object) -> Migration: ...
def hoist_field(*args: object, **kwargs: object) -> Migration: ...
def pipeline(*args: object, **kwargs: object) -> Migration: ...
def compile_migration(*args: object, **kwargs: object) -> CompiledMigration: ...
def compose_migrations(*args: object, **kwargs: object) -> Migration: ...
def invert_migration(migration: Migration, /) -> Migration: ...
def check_coverage(*args: object, **kwargs: object) -> None: ...
def check_existence(*args: object, **kwargs: object) -> None: ...

# ---------------------------------------------------------------------------
# Diff / classification
# ---------------------------------------------------------------------------

class CompatReport:
    compatible: bool
    breaking: list[str]
    def to_dict(self) -> dict[str, object]: ...

class SchemaDiff:
    added_vertices: list[str]
    removed_vertices: list[str]
    def to_dict(self) -> dict[str, object]: ...

def diff_schemas(old: Schema, new: Schema, /) -> SchemaDiff: ...
def diff_and_classify(old: Schema, new: Schema, /) -> CompatReport: ...

# ---------------------------------------------------------------------------
# Instance + I/O
# ---------------------------------------------------------------------------

class Instance:
    def root(self) -> dict[str, object]: ...
    def node_count(self) -> int: ...
    def arc_count(self) -> int: ...
    def validate(self) -> None: ...
    def to_dict(self) -> dict[str, object]: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, schema: Schema, root_vertex: str, payload: str) -> Instance: ...

class IoRegistry:
    def __init__(self) -> None: ...
    def list_protocols(self) -> Iterable[str]: ...
    def emit(self, protocol: str, schema: Schema, instance: Instance) -> bytes: ...
    def parse(self, protocol: str, schema: Schema, data: bytes) -> Instance: ...

# ---------------------------------------------------------------------------
# Lens + protolens chain
# ---------------------------------------------------------------------------

class Lens:
    def get(self, source: object, /) -> tuple[object, Complement]: ...
    def put(self, target: object, complement: Complement, /) -> object: ...
    def compose(self, other: Lens, /) -> Lens: ...
    def check_get_put(self, *args: object, **kwargs: object) -> bool: ...
    def check_put_get(self, *args: object, **kwargs: object) -> bool: ...
    def check_laws(self, *args: object, **kwargs: object) -> bool: ...

class ProtolensChain:
    def to_json(self) -> str: ...
    def compose(self, other: ProtolensChain, /) -> ProtolensChain: ...
    def fuse(self, *args: object, **kwargs: object) -> ProtolensChain: ...
    def instantiate(self, src: Schema, tgt: Schema, /) -> Lens: ...
    @classmethod
    def from_json(cls, payload: str) -> ProtolensChain: ...
    @classmethod
    def auto_generate(
        cls,
        src: Schema,
        tgt: Schema,
        protocol: Protocol,
        stringency: str | None = ...,
    ) -> ProtolensChain: ...
    @classmethod
    def auto_generate_with_hints(
        cls,
        src: Schema,
        tgt: Schema,
        protocol: Protocol,
        hints: object,
        stringency: str | None = ...,
    ) -> ProtolensChain: ...
    @classmethod
    def auto_generate_with_hint_spec(
        cls, *args: object, **kwargs: object
    ) -> ProtolensChain: ...

def auto_generate_lens(
    src: Schema,
    tgt: Schema,
    protocol: Protocol,
    stringency: str | None = ...,
) -> tuple[Lens, float, list[dict[str, object]]]: ...
def auto_generate_lens_candidates(
    *args: object, **kwargs: object
) -> list[tuple[Lens, float]]: ...

# ---------------------------------------------------------------------------
# Expressions
# ---------------------------------------------------------------------------

class Expr:
    def to_dict(self) -> dict[str, object]: ...

def parse_expr(text: str) -> Expr: ...
def pretty_print_expr(expr: Expr) -> str: ...

# ---------------------------------------------------------------------------
# VCS
# ---------------------------------------------------------------------------

class BisectState:
    def to_dict(self) -> dict[str, object]: ...

class Repository:
    @classmethod
    def init(cls, path: str | PathLike[str]) -> Repository: ...
    @classmethod
    def open(cls, path: str | PathLike[str]) -> Repository: ...
    @property
    def working_dir(self) -> str: ...
    def head(self) -> str | None: ...
    def head_state(self) -> str: ...
    def has_staged(self) -> bool: ...
    def list_branches(self) -> list[tuple[str, str]]: ...
    def list_tags(self) -> list[tuple[str, str]]: ...
    def log(self) -> list[dict[str, object]]: ...
    def index(self) -> list[dict[str, object]]: ...
    def add(self, target: Schema, /) -> None: ...
    def commit(self, message: str, author: str, *, skip_verify: bool = ...) -> str: ...
    def amend(self, *args: object, **kwargs: object) -> str: ...
    def reset(self, *args: object, **kwargs: object) -> None: ...
    def clear_index(self) -> None: ...
    def resolve_ref(self, name: str) -> str | None: ...
    def schema_at(self, ref: str) -> Schema: ...
    def create_branch(self, name: str, commit_id: str) -> None: ...
    def create_and_checkout_branch(self, name: str, commit_id: str) -> None: ...
    def checkout_branch(self, name: str) -> None: ...
    def checkout_detached(self, ref: str) -> None: ...
    def delete_branch(self, name: str) -> None: ...
    def force_delete_branch(self, name: str) -> None: ...
    def rename_branch(self, old: str, new: str) -> None: ...
    def create_tag(self, name: str, commit_id: str) -> None: ...
    def create_tag_force(self, name: str, commit_id: str) -> None: ...
    def create_annotated_tag(
        self, name: str, commit_id: str, message: str, author: str
    ) -> None: ...
    def read_annotated_tag(self, name: str) -> dict[str, object]: ...
    def delete_tag(self, name: str) -> None: ...
    def merge(self, *args: object, **kwargs: object) -> str: ...
    def rebase(self, *args: object, **kwargs: object) -> None: ...
    def cherry_pick(self, ref: str) -> str: ...
    def bisect_start(self, *args: object, **kwargs: object) -> BisectState: ...
    def stash_push(self, *args: object, **kwargs: object) -> str: ...
    def stash_pop(self, *args: object, **kwargs: object) -> None: ...
    def stash_apply(self, *args: object, **kwargs: object) -> None: ...
    def stash_drop(self, ref: str) -> None: ...
    def stash_clear(self) -> None: ...
    def stash_list(self) -> list[dict[str, object]]: ...
    def stash_show(self, ref: str) -> dict[str, object]: ...
    def read_reflog(self, ref: str) -> list[dict[str, object]]: ...
    def detect_staleness(self) -> dict[str, object]: ...
    def encode_edit_log_empty(self) -> bytes: ...
    def gc(self) -> None: ...
    def blame_vertex(self, *args: object, **kwargs: object) -> dict[str, object]: ...
    def blame_edge(self, *args: object, **kwargs: object) -> dict[str, object]: ...
    def blame_constraint(self, *args: object, **kwargs: object) -> dict[str, object]: ...

class VcsRepository(Repository): ...

# ---------------------------------------------------------------------------
# Parse + ParseEmitLens
# ---------------------------------------------------------------------------

class ParseEmitLens:
    def parse(self, data: bytes) -> Schema: ...
    def emit(self, schema: Schema) -> bytes: ...

class AstParserRegistry:
    # `extra_grammars` is the cross-cdylib transport surface for
    # companion grammar packs. Each dict carries `name`, `extensions`,
    # `language_ptr`, `node_types_ptr`, `node_types_len`, and the
    # optional `tags_query_ptr`/`tags_query_len`/`grammar_json_ptr`/
    # `grammar_json_len` pairs. End users typically don't touch this
    # directly; `panproto.AstParserRegistry()` (the wrapper factory)
    # builds the list from installed companion entry points.
    def __init__(
        self, extra_grammars: Sequence[Mapping[str, object]] | None = ...
    ) -> None: ...
    def protocol_names(self) -> list[str]: ...
    def detect_language(self, path: str) -> str | None: ...
    def parse_with_protocol(
        self, protocol: str, source: bytes, file_path: str = ...
    ) -> Schema: ...
    def parse_file(self, path: str) -> Schema: ...
    def emit(self, protocol: str, schema: Schema) -> bytes: ...
    def emit_pretty(self, protocol: str, schema: Schema) -> bytes: ...
    def lens(self, protocol: str) -> ParseEmitLens: ...

def available_grammars() -> list[str]: ...
def parse_source_file(*args: object, **kwargs: object) -> Schema: ...

# ---------------------------------------------------------------------------
# Project / git bridge surface (heterogeneous; stubs are minimal)
# ---------------------------------------------------------------------------

class ProjectBuilder:
    def build(self) -> ProjectSchema: ...

class ProjectSchema:
    def to_dict(self) -> dict[str, object]: ...

class GitImportResult:
    def to_dict(self) -> dict[str, object]: ...
